### ISSUE TITLE
LICENSE file desired

### ISSUE THREAD

**Issue by lsm5** [dgnorton/goback#1]
Hi @dgnorton, could you please include a `LICENSE` file containing a suitable opensource license in this repo. We're looking to [package](https://bugzilla.redhat.com/show_bug.cgi?id=1162103) this into Fedora but that can't be done unless this repo includes a license. Thanks!

**Comment by dgnorton** [comment]
@lsm5 I'll add an MIT license in a few minutes.  Out of curiosity, what's goback being used for?

**Comment by ingvagabund** [comment]
Hi @dgnorton, it is a dependency of https://github.com/influxdb/influxdb/. In order to correctly package influxdb in Fedora, it must be debundled. Thus goback must be packaged too. And without the license it is not possible. Thanks

**Comment by dgnorton** [comment]
@ingvagabund ah, okay.  Thanks.  License is there now.
